// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: "AIzaSyXXXX",
        appId: "1:1234567890:web:abcdef",
        messagingSenderId: "1234567890",
        projectId: "motivacionjimmy-a41c2",
        authDomain: "motivacionjimmy-a41c2.firebaseapp.com",
        storageBucket: "motivacionjimmy-a41c2.appspot.com",
      );
    }
    // Android
    return const FirebaseOptions(
      apiKey: "AIzaSyXXXX",
      appId: "1:1234567890:android:abcdef",
      messagingSenderId: "1234567890",
      projectId: "motivacionjimmy-a41c2",
      storageBucket: "motivacionjimmy-a41c2.appspot.com",
    );
  }
}
